AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS-Study CloudFormation"

Parameters:
  #KeyPair
  KeyName:
    Description: "AWS-Study-EC2 KeyPair"
    Type: AWS::EC2::KeyPair::KeyName

  #ResourcesPrefix
  ResourcesPrefix:
    Description: "Resources-Name Prefix"
    Type: String
    Default: AWS-Study

  #MyIP
  MyIP:
    Description: "Allow SSH"
    Type: String
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$'

  #RDS
  RDSMasterUserName:
    Description: "Must be 1 to 16 letters or numbers. First character must be a letter."
    Type: String
    AllowedPattern: '^[a-zA-Z]{1}[a-zA-Z0-9]{0,15}$'

  RDSMasterUserPassword:
    Description: "Constraints: Must contain from 8 to 41 characters."
    Type: String
    AllowedPattern: '^[\x21-\x7E&&[^/@"]]{8,41}$'

  DBSubnetGroupName:
    Type: String
    Default: "rds-ec2-db-subnet-group-4"

  DBName:
    Description: "Must contain 1 to 64 letters or numbers."
    Type: String
    Default: "AWSStudy"
    AllowedPattern: '^[a-zA-Z0-9]{1,64}$'

Resources:
  # IGW
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${ResourcesPrefix}-IGW"

  AttachIGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref AWSStudyVPC
      InternetGatewayId: !Ref InternetGateway

  # VPC
  AWSStudyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags: 
        - Key: Name
          Value: !Sub "${ResourcesPrefix}-VPC"

  # Subnet
  PublicSubnetAZ1a:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select 
        - 0
        - Fn::GetAZs: !Ref AWS::Region
      CidrBlock: 10.0.0.0/20
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: Name
          Value: !Sub "${ResourcesPrefix}-subnet-public1"
      VpcId: !Ref AWSStudyVPC

  AssoPubSub1aRT:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PubSubrtb
      SubnetId: !Ref PublicSubnetAZ1a

  PrivateSubnetAZ1a:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select 
        - 0
        - Fn::GetAZs: !Ref AWS::Region
      CidrBlock: 10.0.128.0/20
      MapPublicIpOnLaunch: false
      Tags: 
        - Key: Name
          Value: !Sub "${ResourcesPrefix}-subnet-private1"
      VpcId: !Ref AWSStudyVPC

  AssoPvtSub1aRT:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PvtSub1rtb
      SubnetId: !Ref PrivateSubnetAZ1a

  PublicSubnetAZ1c:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select 
        - 1
        - Fn::GetAZs: !Ref AWS::Region
      CidrBlock: 10.0.16.0/20
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: Name
          Value: !Sub "${ResourcesPrefix}-subnet-public2"
      VpcId: !Ref AWSStudyVPC

  AssoPubSub1cRT:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PubSubrtb
      SubnetId: !Ref PublicSubnetAZ1c

  PrivateSubnetAZ1c:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select 
        - 1
        - Fn::GetAZs: !Ref AWS::Region
      CidrBlock: 10.0.144.0/20
      MapPublicIpOnLaunch: false
      Tags: 
        - Key: Name
          Value: !Sub "${ResourcesPrefix}-subnet-private2"
      VpcId: !Ref AWSStudyVPC

  AssoPvtSub1cRT:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PvtSub2rtb
      SubnetId: !Ref PrivateSubnetAZ1c

  # rtb
  PubSubrtb:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref AWSStudyVPC
      Tags:
        - Key: Name
          Value: !Sub "${ResourcesPrefix}-rtb-public"

  PvtSub1rtb:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref AWSStudyVPC
      Tags:
        - Key: Name
          Value: !Sub "${ResourcesPrefix}-rtb-private1"

  PvtSub2rtb:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref AWSStudyVPC
      Tags:
        - Key: Name
          Value: !Sub "${ResourcesPrefix}-rtb-private2"

  # Route
  PubSubInternet:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PubSubrtb
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  # EC2SecurityGroup
  AWSStudyEC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow SSH,http,https"
      GroupName: !Sub "${ResourcesPrefix}-EC2-SG"
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub "${MyIP}/32"
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      VpcId: !Ref AWSStudyVPC

  # RDSSecurityGroup
  AWSStudyRDSSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow EC2 Accsess"
      GroupName: !Sub "${ResourcesPrefix}-RDS-SG"
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref AWSStudyEC2SG
      VpcId: !Ref AWSStudyVPC

  # EC2
  AWSStudyEC2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Select 
        - 0
        - Fn::GetAZs: !Ref AWS::Region
      DisableApiTermination: true
      ImageId: ami-03598bf9d15814511
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref AWSStudyEC2SG
      SubnetId: !Ref PublicSubnetAZ1a
      Tags:
        - Key: Name
          Value: !Sub "${ResourcesPrefix}-EC2"
      Tenancy: default

  # RDS
  AWSStudyRDS:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      AvailabilityZone: !Select 
        - 0
        - Fn::GetAZs: !Ref AWS::Region
      Engine: mysql
      EngineVersion: "8.0.39"
      DBInstanceIdentifier: !Sub "${ResourcesPrefix}-RDS-CFn"
      MasterUsername: !Ref RDSMasterUserName
      MasterUserPassword: !Ref RDSMasterUserPassword
      DBInstanceClass: db.t4g.micro
      StorageType: gp2
      AllocatedStorage: 20
      MaxAllocatedStorage: 20
      DBSubnetGroupName: !Ref AWSStudyRDSSubnetGroup
      VPCSecurityGroups:
        - !Ref AWSStudyRDSSG
      CACertificateIdentifier: rds-ca-rsa2048-g1
      Port: 3306
      DBName: !Ref DBName
      StorageEncrypted: true
      EnableCloudwatchLogsExports:
        - audit
        - error
        - general
        - slowquery
      PubliclyAccessible: false
      MultiAZ: false
      DeletionProtection: true
      BackupRetentionPeriod: 1

  # RDSDBSubnetGroup
  AWSStudyRDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub "${ResourcesPrefix} DBSubnetGroup"
      DBSubnetGroupName: !Ref DBSubnetGroupName
      SubnetIds:
        - !Ref PrivateSubnetAZ1a
        - !Ref PrivateSubnetAZ1c

  # ELB
  AWSStudyELB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Name: !Sub "${ResourcesPrefix}-ALB"
      Scheme: internet-facing
      IpAddressType: ipv4
      Subnets:
        - !Ref PublicSubnetAZ1a
        - !Ref PublicSubnetAZ1c
      SecurityGroups:
        - !Ref AWSStudyELBSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${ResourcesPrefix}-ALB"

  ELBListner:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref AWSStudyELB
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref AWSStudyELBTG
      Port: 80
      Protocol: HTTP
      
  AWSStudyELBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow http"
      GroupName: !Sub "${ResourcesPrefix}-ALB-SG"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      VpcId: !Ref AWSStudyVPC

  AWSStudyELBTG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: "/"
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200,300,301
      Name: !Sub "${ResourcesPrefix}-TG"
      Port: 8080
      Protocol: HTTP
      TargetType: instance
      Targets:
        - Id: !Ref AWSStudyEC2
      VpcId: !Ref AWSStudyVPC
